language: java

jdk:
  - oraclejdk8

branches:
  only:
  - master
  
script:
  - mvn clean install
  - java -cp target/gameDataWrapper-0.6.0-SNAPSHOT.jar org.wuprotos.wrappers.GenerateJSON ./versions/latest/GameDataWrapper.bytes
